name: wallpaper
description: A simple wallpaper app by ablinfotech.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider:
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.3
  flutter_snake_navigationbar: ^0.5.0
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  hexcolor: ^2.0.4
  url_launcher: ^6.0.9
  flutter_cache_manager: ^3.1.2
  image_gallery_saver: ^1.6.9
  dio: ^4.0.0
  permission_handler: ^10.0.0
  image_downloader: ^0.31.0
  shared_preferences: ^2.0.15
  page_transition: "^2.0.4"
  lottie: ^1.4.2
  flutter_staggered_animations: ^1.0.0
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
  # To add assets to your application, add an assets section, like this:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher-icon.png"